on:
  workflow_call:
    inputs:
        head-ref:
            required: true
            type: string
        is-draft:
            required: true
            type: boolean
    secrets:
        JIRA_BASE_URL:
          required: false
        JIRA_USER_EMAIL:
          required: false
        JIRA_API_TOKEN:
          required: false

jobs:
  transition-issue:
    if: ${{ !inputs.is-draft
         && secrets.JIRA_BASE_URL != '' 
         && secrets.JIRA_USER_EMAIL != '' 
         && secrets.JIRA_API_TOKEN != '' }}
    name: Transition Issue to In Review
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      id: find
      uses: atlassian/gajira-find-issue-key@v3
      continue-on-error: true
      with:
        string: ${{ inputs.head-ref }}

    - name: Transition issue
      uses: atlassian/gajira-transition@v3
      continue-on-error: true
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: Review
